
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.14.6-300.fc42.x86_64 - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/FindThreads.cmake:99 (CHECK_CXX_SOURCE_COMPILES)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Dependencies.cmake:34 (_qt_internal_find_third_party_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:162 (include)"
      - "CMakeLists.txt:7 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-LwaaWC"
      binary: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-LwaaWC"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-20"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/platforms;/home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/cmake/Modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-LwaaWC'
        
        Run Build Command(s): /home/mv/Qt/Tools/CMake/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_feb76/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_feb76.dir/build.make CMakeFiles/cmTC_feb76.dir/build
        gmake[1]: Entering directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-LwaaWC'
        Building CXX object CMakeFiles/cmTC_feb76.dir/src.cxx.o
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ -DCMAKE_HAVE_LIBC_PTHREAD   -MD -MT CMakeFiles/cmTC_feb76.dir/src.cxx.o -MF CMakeFiles/cmTC_feb76.dir/src.cxx.o.d -o CMakeFiles/cmTC_feb76.dir/src.cxx.o -c /home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-LwaaWC/src.cxx
        Linking CXX executable cmTC_feb76.js
        /home/mv/Qt/Tools/CMake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_feb76.dir/link.txt --verbose=1
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_feb76.dir/objects1.rsp -o cmTC_feb76.js
        cache:INFO: generating system asset: symbol_lists/dae99d994d603fb13aa7edd6245a890f9752f2c4.json... (this will be cached in "/home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/cache/symbol_lists/dae99d994d603fb13aa7edd6245a890f9752f2c4.json" for subsequent builds)
        cache:INFO:  - ok
        gmake[1]: Leaving directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-LwaaWC'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapAtomic.cmake:36 (check_cxx_source_compiles)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake:43 (include)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:7 (find_package)"
    checks:
      - "Performing Test HAVE_STDATOMIC"
    directories:
      source: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-IK7ezi"
      binary: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-IK7ezi"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-20"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/platforms;/home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/cmake/Modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_STDATOMIC"
      cached: true
      stdout: |
        Change Dir: '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-IK7ezi'
        
        Run Build Command(s): /home/mv/Qt/Tools/CMake/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_8f20d/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_8f20d.dir/build.make CMakeFiles/cmTC_8f20d.dir/build
        gmake[1]: Entering directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-IK7ezi'
        Building CXX object CMakeFiles/cmTC_8f20d.dir/src.cxx.o
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ -DHAVE_STDATOMIC   -MD -MT CMakeFiles/cmTC_8f20d.dir/src.cxx.o -MF CMakeFiles/cmTC_8f20d.dir/src.cxx.o.d -o CMakeFiles/cmTC_8f20d.dir/src.cxx.o -c /home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-IK7ezi/src.cxx
        Linking CXX executable cmTC_8f20d.js
        /home/mv/Qt/Tools/CMake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8f20d.dir/link.txt --verbose=1
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_8f20d.dir/objects1.rsp -o cmTC_8f20d.js
        gmake[1]: Leaving directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-IK7ezi'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:23 (check_cxx_source_compiles)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake:43 (include)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:7 (find_package)"
    checks:
      - "Performing Test HAVE_GETTIME"
    directories:
      source: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-oqw6jG"
      binary: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-oqw6jG"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-20"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/platforms;/home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/cmake/Modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_GETTIME"
      cached: true
      stdout: |
        Change Dir: '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-oqw6jG'
        
        Run Build Command(s): /home/mv/Qt/Tools/CMake/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_721be/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_721be.dir/build.make CMakeFiles/cmTC_721be.dir/build
        gmake[1]: Entering directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-oqw6jG'
        Building CXX object CMakeFiles/cmTC_721be.dir/src.cxx.o
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ -DHAVE_GETTIME   -MD -MT CMakeFiles/cmTC_721be.dir/src.cxx.o -MF CMakeFiles/cmTC_721be.dir/src.cxx.o.d -o CMakeFiles/cmTC_721be.dir/src.cxx.o -c /home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-oqw6jG/src.cxx
        Linking CXX executable cmTC_721be.js
        /home/mv/Qt/Tools/CMake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_721be.dir/link.txt --verbose=1
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_721be.dir/objects1.rsp -o cmTC_721be.js
        gmake[1]: Leaving directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-oqw6jG'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/FindWrapRt.cmake:34 (check_cxx_source_compiles)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreDependencies.cmake:38 (_qt_internal_find_third_party_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Core/Qt6CoreConfig.cmake:45 (include)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake:43 (include)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:7 (find_package)"
    checks:
      - "Performing Test HAVE_SHM_OPEN_SHM_UNLINK"
    directories:
      source: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-rP6wby"
      binary: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-rP6wby"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-20"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/platforms;/home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/cmake/Modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_SHM_OPEN_SHM_UNLINK"
      cached: true
      stdout: |
        Change Dir: '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-rP6wby'
        
        Run Build Command(s): /home/mv/Qt/Tools/CMake/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_5ecd2/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_5ecd2.dir/build.make CMakeFiles/cmTC_5ecd2.dir/build
        gmake[1]: Entering directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-rP6wby'
        Building CXX object CMakeFiles/cmTC_5ecd2.dir/src.cxx.o
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ -DHAVE_SHM_OPEN_SHM_UNLINK   -MD -MT CMakeFiles/cmTC_5ecd2.dir/src.cxx.o -MF CMakeFiles/cmTC_5ecd2.dir/src.cxx.o.d -o CMakeFiles/cmTC_5ecd2.dir/src.cxx.o -c /home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-rP6wby/src.cxx
        Linking CXX executable cmTC_5ecd2.js
        /home/mv/Qt/Tools/CMake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5ecd2.dir/link.txt --verbose=1
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_5ecd2.dir/objects1.rsp -o cmTC_5ecd2.js
        gmake[1]: Leaving directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-rP6wby'
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CheckCXXSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules/FindEGL.cmake:128 (check_cxx_source_compiles)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:36 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiDependencies.cmake:39 (_qt_internal_find_third_party_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake:43 (include)"
      - "/home/mv/Qt/Tools/CMake/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickDependencies.cmake:45 (_qt_internal_find_qt_dependencies)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake:43 (include)"
      - "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)"
      - "CMakeLists.txt:7 (find_package)"
    checks:
      - "Performing Test HAVE_EGL"
    directories:
      source: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-k1tXkx"
      binary: "/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-k1tXkx"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-20"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/platforms;/home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/cmake/Modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake/Qt6/3rdparty/kwin"
      QT_ADDITIONAL_PACKAGES_PREFIX_PATH: ""
      QT_CHAINLOAD_TOOLCHAIN_FILE: ""
      QT_TOOLCHAIN_INCLUDE_FILE: ""
      QT_TOOLCHAIN_RELOCATABLE_CMAKE_DIR: "/home/mv/Qt/6.9.0/wasm_multithread/lib/cmake"
      QT_TOOLCHAIN_RELOCATABLE_PREFIX: ""
    buildResult:
      variable: "HAVE_EGL"
      cached: true
      stdout: |
        Change Dir: '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-k1tXkx'
        
        Run Build Command(s): /home/mv/Qt/Tools/CMake/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_ee84f/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_ee84f.dir/build.make CMakeFiles/cmTC_ee84f.dir/build
        gmake[1]: Entering directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-k1tXkx'
        Building CXX object CMakeFiles/cmTC_ee84f.dir/src.cxx.o
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ -DHAVE_EGL   -MD -MT CMakeFiles/cmTC_ee84f.dir/src.cxx.o -MF CMakeFiles/cmTC_ee84f.dir/src.cxx.o.d -o CMakeFiles/cmTC_ee84f.dir/src.cxx.o -c /home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-k1tXkx/src.cxx
        Linking CXX executable cmTC_ee84f.js
        /home/mv/Qt/Tools/CMake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ee84f.dir/link.txt --verbose=1
        /home/mv/Dokumenti/emscriptenSDK/emsdk/upstream/emscripten/em++ @CMakeFiles/cmTC_ee84f.dir/objects1.rsp -o cmTC_ee84f.js
        gmake[1]: Leaving directory '/home/mv/wasm/CMakeFiles/CMakeScratch/TryCompile-k1tXkx'
        
      exitCode: 0
...
